2021-10-04 19:41:37,090 (18865/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-10-04 19:41:37,090 (18865/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-10-04 19:41:37,092 (18865/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 594, in connect\n    raise e\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 581, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2021-10-04 19:42:18,161 (18933/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-10-04 19:42:18,162 (18933/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-10-04 19:42:21,687 (18933/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 581, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 590, in connect\n    pgexecute = PGExecute(\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "joaom"\nconnection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "joaom"\n\n'
2021-10-04 19:42:51,717 (19005/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-10-04 19:42:51,717 (19005/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-10-04 19:43:30,957 (19005/MainThread) pgcli.pgexecute ERROR - sql: 'table co', error: UndefinedTable('relation "co" does not exist\nLINE 1: table co\n              ^\n')
2021-10-04 19:43:30,958 (19005/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: relation "co" does not exist\nLINE 1: table co\n              ^\n\n'
2021-10-04 19:43:39,436 (19005/MainThread) pgcli.pgexecute ERROR - sql: 'table user', error: SyntaxError('syntax error at or near "user"\nLINE 1: table user\n              ^\n')
2021-10-04 19:43:39,437 (19005/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "user"\nLINE 1: table user\n              ^\n\n'
2021-10-04 19:43:50,716 (19005/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2021-10-04 19:43:50,716 (19005/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2021-10-04 19:47:38,295 (19005/MainThread) pgcli.pgexecute ERROR - sql: '\\quit', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\quit\n        ^\n')
2021-10-04 19:47:38,295 (19005/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\quit\n        ^\n\n'
2021-10-05 19:16:57,774 (834/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-10-05 19:16:57,776 (834/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-10-05 19:16:57,794 (834/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 594, in connect\n    raise e\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 581, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/linuxbrew/.linuxbrew/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2021-10-05 19:19:58,473 (2120/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-10-05 19:19:58,473 (2120/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
